[build]
  base    = "frontend-user"
  command = "npm run build"
  publish = "frontend-user/dist"

[build.environment]
  VITE_API_URL = "https://web-production-04206.up.railway.app"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
