-- 034_business_codes_and_zones.sql
-- Two related changes:
--
--  1. Every business now has a 4-digit business_code, used by Dander Node
--     phones during first-launch setup (operator types the code, the app
--     resolves it to a business_id via the public lookup endpoint).
--
--     Codes are auto-generated by a BEFORE INSERT trigger when the
--     application doesn't supply one. Existing rows are backfilled in
--     this same migration.
--
--  2. phone_counter_readings gains zone_name / zone_type / business_id
--     so each device's uploads can be attributed to a business and a
--     named zone (entrance / display / till / general).

-- ── businesses.business_code ──────────────────────────────────────────────

ALTER TABLE businesses ADD COLUMN IF NOT EXISTS business_code VARCHAR(4) UNIQUE;

CREATE OR REPLACE FUNCTION generate_business_code() RETURNS VARCHAR AS $$
DECLARE
  candidate VARCHAR(4);
  attempts  INT := 0;
BEGIN
  LOOP
    candidate := lpad((floor(random() * 9000) + 1000)::int::text, 4, '0');
    PERFORM 1 FROM businesses WHERE business_code = candidate;
    IF NOT FOUND THEN RETURN candidate; END IF;
    attempts := attempts + 1;
    IF attempts > 1000 THEN
      -- ~10k possible codes; if we've collided this many times the space
      -- is effectively exhausted. Fail loudly so we notice.
      RAISE EXCEPTION 'unable to allocate a unique business_code after % attempts', attempts;
    END IF;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION businesses_assign_code() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.business_code IS NULL THEN
    NEW.business_code := generate_business_code();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_businesses_business_code ON businesses;
CREATE TRIGGER trg_businesses_business_code
  BEFORE INSERT ON businesses
  FOR EACH ROW EXECUTE FUNCTION businesses_assign_code();

-- Backfill: every existing row missing a code gets one. Per-row loop so
-- each call reads the latest state of the column (collisions impossible).
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN SELECT id FROM businesses WHERE business_code IS NULL LOOP
    UPDATE businesses SET business_code = generate_business_code() WHERE id = r.id;
  END LOOP;
END $$;

-- ── phone_counter_readings: zone + business_id ───────────────────────────

ALTER TABLE phone_counter_readings ADD COLUMN IF NOT EXISTS zone_name   VARCHAR(100);
ALTER TABLE phone_counter_readings ADD COLUMN IF NOT EXISTS zone_type   VARCHAR(30);
ALTER TABLE phone_counter_readings ADD COLUMN IF NOT EXISTS business_id INTEGER REFERENCES businesses(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_phone_counter_business_zone
  ON phone_counter_readings(business_id, zone_name, timestamp DESC);
