apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.applinks'
version = '0.1.0'

android {
  namespace 'expo.modules.applinks'
  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 24)
    compileSdkVersion safeExtGet('compileSdkVersion', 34)
  }
}
